`timescale 1ns/1ps
//=============================================================
// riscv_spi_if.sv
// DUT-pin interface for riscv_spi_soc_top. PCLK is generated by
// tb_top and passed in; everything else lives here so the UVM
// driver/monitor can get at the pins through a virtual interface
// instead of hard hierarchical paths.
//=============================================================
interface riscv_spi_if (input logic PCLK);

    logic PRESETn;
    logic SCLK;
    logic MOSI;
    logic MISO;
    logic SS_N;

    // Monitor samples everything on the sampling edge only -> no
    // race with the DUT's own posedge PCLK always_ff blocks.
    clocking mon_cb @(posedge PCLK);
        input PRESETn, SCLK, MOSI, MISO, SS_N;
    endclocking

    // Driver only ever drives MISO (the one pin the TB owns).
    clocking drv_cb @(posedge PCLK);
        output MISO;
        input  PRESETn, SCLK, MOSI, SS_N;
    endclocking

    modport MON (clocking mon_cb);
    modport DRV (clocking drv_cb, output PRESETn);

endinterface : riscv_spi_if
